name: 'git-ftp-action'
author: 'Aurelien Barbier-Accary, from Sebastian Popp <git-ftp-action@sebastianpopp.com>'
description: 'Uses git-ftp and GitHub actions to deploy a GitHub repository to a FTP server.'
inputs:
  url:
    required: true
    description: 'FTP url, including the root directory of the project'
  user:
    required: true
    description: 'FTP login'
  password:
    required: false
    description: 'FTP password'
  syncroot:
    required: false
    default: '.'
    description: 'Local directory to sync from as if it were the git project root path'
  options:
    required: false
    default: '--auto-init'
    description: 'Additional options'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'upload-cloud'
